id: hl7.fhir.it.lab-report
canonical: http://hl7.it/fhir/lab-report
name: HL7ITLabReport
title: HL7 FHIR Implementation Guide Laboratory Report
description: HL7 FHIR Implementation Guide Laboratory Report specifica come utilizzare lo standard HL7 FHIR per documentare un referto di medicina di laboratorio.
status: active # draft | active | retired | unknown
version: 0.2.0
fhirVersion: 4.0.1 # https://www.hl7.org/fhir/valueset-FHIR-version.html
copyrightYear: 2022+
releaseLabel: trial-use # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use

publisher:
  - name: HL7 Italia
    url: https://hl7.it
contact:
  - name: HL7 Italia
    telecom:
      - system: url
        value: https://hl7.it

jurisdiction: urn:iso:std:iso:3166#IT "Italy"

dependencies:
  #hl7.fhir.it.base: current
  hl7.fhir.it.terminology: current

  hl7.fhir.eu.laboratory: current  # ONLY for the ci build

  #hl7.fhir.eu.laboratory: 0.1.0-ballot
  # hl7.fhir.uv.ips: current # ONLY for the ci build
  hl7.fhir.uv.ips: 1.1.0 
  hl7.fhir.extensions.r5: 4.0.1
parameters: #see https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters
#  produce-jekyll-data: true

  special-url:
    - http://hl7.org/fhir/StructureDefinition/address-official
    - http://hl7.it/fhir/StructureDefinition/composition-basedOn-order-or-requisition-it
    - http://hl7.it/fhir/StructureDefinition/composition-dataenterer-it
    - http://hl7.it/fhir/StructureDefinition/dataEnterer-time
    - http://hl7.it/fhir/StructureDefinition/patient-codeableBirthPlace
    - http://hl7.it/fhir/StructureDefinition/patient-occupation-it
    - http://hl7.it/fhir/StructureDefinition/patient-qualification-it
    - http://hl7.it/fhir/StructureDefinition/recordCertification
    - http://hl7.it/fhir/StructureDefinition/address-dug
  #  - http://hl7.it/fhir/StructureDefinition/information-recipient

pages:
  index.md:
    title: Home
  # contesto.md:
  #   title: Contesto
  downloads.md:
    title: Downloads
  # methodology.md:
  #   title: Metodologia
  #scenario.md:
  #  title: Scenario 
  modelliLogici.md:
    title: Modelli Logici  

menu:
  IG Home: index.html
  Sommario: toc.html
  # Contesto: contesto.html
    # Contesto: 
    # Metodologia: methodology.html
  Specifiche:
    # Scenari: scenario.html
    Modelli Logici: modelliLogici.html
  Indice Artefatti: artifacts.html
  Support:
    FHIR Spec: new-tab http://hl7.org/fhir/R4/index.html
    Maps: new-tab https://build.fhir.org/ig/hl7-it/cda2fhir/index.html
    Downloads: downloads.html

groups:
  LabReportLogicalModel:
    name:  Linee Guida Referto di Laboratorio
    description: Modelli Logici che rappresentano il contenuto informativo del Referto di Laboratorio.
    resources:
      - StructureDefinition/RefertoLaboratorio
      - StructureDefinition/SoggettoCura
      - StructureDefinition/Autore
      - StructureDefinition/Validatore
      - StructureDefinition/Firmatario
      - StructureDefinition/Destinatario
      - StructureDefinition/Richiesta
      - StructureDefinition/Risultato
      - StructureDefinition/Campione
      - StructureDefinition/Organizer
  LabReportDOC:
    name: Profili Risorse Documento FHIR
    description: Profili risorse necessarie per produrre il documento FHIR Lab Report.
    resources:
      - StructureDefinition/bundle-it-lab
      - StructureDefinition/composition-it-lab
      - StructureDefinition/observation-doc-it-lab
      - StructureDefinition/diagnosticreport-it-lab
      - StructureDefinition/patient-it-lab
  LabReportRES:
    name: Profili Risorse  
    description: Profili risorse specifiche per il dominio di Lab Report.
    resources:
      - StructureDefinition/observation-it-lab
      - StructureDefinition/specimen-it-lab
      - StructureDefinition/media-it-lab      
      - StructureDefinition/encounter-it-lab
      - StructureDefinition/servicerequest-it-lab
      - StructureDefinition/location-it-lab
      - StructureDefinition/practitionerrole-it-lab
      - StructureDefinition/practitionerrole-MMGPLS-it-lab
      - StructureDefinition/practitioner-it-lab
      - StructureDefinition/organization-it-lab
      - StructureDefinition/organizationOperatore-it-lab
      - StructureDefinition/device-it-lab
      - StructureDefinition/substance-additive-specimen-it-lab
      - StructureDefinition/observation-grouping-it-lab
      