id: hl7.fhir.it.lab-report
canonical: http://hl7.it/fhir/lab-report
name: HL7ITLabReport
title: HL7 FHIR Implementation Guide Laboratory Report
description: HL7 FHIR Implementation Guide Laboratory Report specifica come utilizzare lo standard HL7 FHIR per documentare un referto di medicina di laboratorio.
status: draft # draft | active | retired | unknown
version: 0.1.0
fhirVersion: 4.0.1 # https://www.hl7.org/fhir/valueset-FHIR-version.html
copyrightYear: 2022+
releaseLabel: ci-build # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use

publisher:
  - name: HL7 Italia
    url: https://hl7.it
contact:
  - name: HL7 Italia
    telecom:
      - system: url
        value: https://hl7.it

jurisdiction: urn:iso:std:iso:3166#IT "Italy"

dependencies:
  hl7.fhir.it.base: current
  #hl7.fhir.it.terminology: 0.1.1
  hl7.fhir.extensions.r5: 4.0.1
  hl7.fhir.it.cda2fhir: current

pages:
  index.md:
    title: Home
  # contesto.md:
  #   title: Contesto
  downloads.md:
    title: Downloads
  # methodology.md:
  #   title: Metodologia
  scenario.md:
    title: Scenario 
  modelliLogici.md:
    title: Modelli Logici  

menu:
  IG Home: index.html
  Sommario: toc.html
  # Contesto: contesto.html
    # Contesto: 
    # Metodologia: methodology.html
  Specifiche:
    Scenari: scenario.html
    Modelli Logici: modelliLogici.html
  Indice Artefatti: artifacts.html
  Support:
    FHIR Spec: new-tab http://hl7.org/fhir/R4/index.html
    Maps: new-tab https://build.fhir.org/ig/hl7-it/cda2fhir/index.html
    Downloads: downloads.html

groups:
  LabReportDOC:
    name: Profili Risorse Documento FHIR
    description: Profili risorse necessarie per produrre il documento FHIR Lab Report.
    resources:
      - StructureDefinition/bundle-it-lab
      - StructureDefinition/composition-it-lab
      - StructureDefinition/observation-doc-it-lab
  LabReportRES:
    name: Profili Risorse  
    description: Profili risorse specifiche per il dominio di Lab Report.
    resources:
      - StructureDefinition/diagnosticreport-it-lab
      - StructureDefinition/observation-it-lab
      - StructureDefinition/specimen-it-lab
      - StructureDefinition/media-it-lab
      - StructureDefinition/patient-it-lab
      - StructureDefinition/encounter-it-lab
      - StructureDefinition/servicerequest-it-lab
      - StructureDefinition/location-it-lab
      - StructureDefinition/practitionerrole-it-lab
      - StructureDefinition/practitioner-it-lab
      - StructureDefinition/organization-it-lab
      - StructureDefinition/device-it-lab
      - StructureDefinition/specimen-additive-substance-it-lab
      - StructureDefinition/observation-grouping-it-lab
